name: flexi_productimage_slider
description: An image slider to represent your products..:)
version: 1.1.0
repository: https://github.com/Dharini17/flexi_productimage_slider
documentation: https://pub.dev/documentation/flexi_productimage_slider

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

screenshots:
  - description: 'This image shows example of flexi_productimage_slider'
    path: screenshots/preview.png